# Introduzione a NumPy

## Indice

# 1. NumPy <a id=numpy> </a>

Dal [sito ufficiale](http://www.numpy.org/) di NumPy:
> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

>Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Tutorial ufficiale: [Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html).

In [ ]:
import numpy as np

%load_ext autoreload
%autoreload 2

# 2. `ndarray`

# 2.1 Creare un array <a id=creare_array> </a>

### `numpy.array()`

In [ ]:
a = np.array(
    [[1, 2, 3], 
     [4, 5, 6]]
)

print("Tipo: {}".format(type(a)))
print("Contenuto della variabile:")
print(a)

### `numpy.arange()`

In [ ]:
a = np.arange(6)

print("Contenuto della variabile:")
print(a)

### `numpy.zeros()`

In [ ]:
a = np.zeros((2, 3))

print("Contenuto della variabile:")
print(a)

### `numpy.ones()`

In [ ]:
a = np.ones((2, 3))

print("Contenuto della variabile:")
print(a)

### `numpy.random.random()`

In [ ]:
a = np.random.random((3, 2))

print("Contenuto della variabile:")
print(a)

### `numpy.empty()`

In [ ]:
a = np.empty((2, 3))

print("Contenuto della variabile:")
print(a)

### Esercizio

Ottenere il seguente array utilizzando esclusivamente `numpy.arange()`:
```python
[10, 20, 30, 40, 50, 60, 70, 80, 90]
```

## 2.2 Caratteristiche di un `ndarray` <a id=caratteristiche_array> </a>

### `numpy.ndarray.ndim`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Numero di dimensioni: {}".format(a.ndim))

### `numpy.ndarray.shape`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Dimensioni: {}".format(a.shape))

### `numpy.ndarray.size`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Numero di elementi: {}".format(a.size))

### `numpy.ndarray.itemsize`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Dimensione in bytes di ogni elemento dell'array: {}".format(a.itemsize))

###  `numpy.ndarray.dtype `

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Tipo degli elmenti dell'array: {}".format(a.dtype))

### Esercizio

Sapendo che il tipo degli elementi è `int64`, avremmo potuto prevedere la dimensione in bytes? Motivare la risposta.

## 2.3 Cambiare la forma di un array <a id=cambiare_forma_array> </a>

###  `numpy.ndarray.reshape() `

In [ ]:
a = np.arange(6)

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nModificare le dimensioni dell'array:")
a = a.reshape(3, 2)
print("a = a.reshape(3, 2)")

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

###  `numpy.diag() `

In [ ]:
a = np.ones(2)

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nCreare una matrice diagonale a partire da un vettore:")
print("a = np.diag(a)")
a = np.diag(a)

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

### Esercizio

Creare il seguente array usando `numpy.arange()` e `numpy.diag()`:
```python
[[0 0 0]
 [0 1 0]
 [0 0 2]]
 ```

###  `numpy.ndarray.T `

In [ ]:
a = np.ones((2, 3))

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nTrasporre la matrice:")
print("a = a.T")
a = a.T

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

### `numpy.newaxis`

In [ ]:
a = np.arange(5)

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nAggiungere una dimensione all'array:")
print("a = a[:, np.newaxis]")
a = a[:, np.newaxis] # equivalente a: a[:, None]

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

## 3. Algebra lineare <a id=algebra_lineare> </a>

### Operazioni di base con scalari

In [ ]:
a = np.arange(20, 60, 10).reshape(2, -2)

print("Contenuto della variabile:")
print(a)

print("\nDivido per 10 e aggiungo 5:")
print("a = (a / 10) + 5")
a = (a / 10) + 5

print("\nContenuto della variabile:")
print(a)

### Esercizio

Studiare il concetto di [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html). 

Se
```python
a = np.empty((2, 1, 2, 2))
b = np.empty((5, 1, 1))
c = a * b
```
qual'è la dimensione di `c`? provare a rispondere e, solo sucessivamente, verificarlo scrivendo l'opportuno codice.

### `*` ([prodotto di Hadamard](https://it.wikipedia.org/wiki/Moltiplicazione_di_matrici#Costruzioni_alternative) o prodotto puntuale)

In [ ]:
a = np.array(
    [[2, 1], 
     [0, 3]]
)
b = np.array(
    [[2, 0], 
     [1, 3]]
)

print('Contenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

print('\nProdotto di Hadamard tra "a" e "b":')
print("c = a * b")
c = a * b

print('\nContenuto della variabile "c":')
print(c)

### `numpy.dot()` ([prodotto scalare](https://it.wikipedia.org/wiki/Prodotto_scalare) o [prodotto matriciale](https://it.wikipedia.org/wiki/Moltiplicazione_di_matrici) se `ndim` è uguale a 2)

In [ ]:
a = np.array(
    [[2, 1], 
     [0, 3]]
)
b = np.array(
    [[2, 0], 
     [1, 3]]
)

print('Contenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

print('\nProdotto scalare tra "a" e "b":')
print("c = np.dot(a, b)")
c = np.dot(a, b) # equivalente a: c = a.dot(b)

print('\nContenuto della variabile "c":')
print(c)

### Esercizio

Completare il metodo `fit()` della classe `RegressioneLineare` in `msbd/modello_lineare/regressione_lineare.py`.

Si ricorda che la stima dei coefficienti con il metodo dei minimi quadrati è data da
$$
\hat{\beta}=(X^TX)^{-1}X^Ty
$$

>Suggerimento: leggere la documentazione di `numpy.linalg.inv()`.

Testare la funzione utilizzando pytest.

In [ ]:
from msbd.modello_lineare import  RegressioneLineare
import inspect

print(inspect.getsource(RegressioneLineare))

In [ ]:
!pytest -v msbd/tests/test_regressione_lineare.py

# DA FINIRE

In [ ]:
beta = np.array([[2], 
                 [5]])
print("beta:")
print(beta)

num_oss = 100

np.random.seed(42)

X = np.hstack([np.ones((num_oss, 1)), np.random.random((num_oss, 1))])
print("\nPrime cinque righe di X:")
print(X[:5])

y = X.dot(beta) + np.random.normal(0, 0.5, (num_oss, 1))
print("\nPrimi cinque valori di y:")
print(y[:5])

plt.scatter(X[:, 1], y)
plt.xlabel("X[:, 1]")
plt.ylabel("y")
plt.grid()
plt.show()

### Verifica dell'implementazione

In [ ]:
beta_mq = minimi_quadrati(X, y)
print("beta:")
print(beta)
print("\nStima minimi quadrati di beta:")
print(beta_mq.round(2))

## Funzioni matematiche

In [ ]:
a = np.arange(1, 5).reshape((2, 2))
print('a:')
print(a)

### numpy.sin

In [ ]:
print("np.sin(a):")
np.sin(a)

### numpy.cos

In [ ]:
print("np.cos(a):")
np.cos(a)

### Esercizio

Siano
```python
a = np.array([np.cos(np.pi / 6), 0.5])
b = np.array([0.5, np.cos(np.pi / 6)])
```
1. Disegnare $a$ e $b$, qual'è l'angolo $\theta$ in radianti tra i due vettori?
2. Verificare che $a \cdot b = |a| \times |b| \times \cos(\theta)$.

> Suggerimento: per $|\cdot|$ vedere `np.linalg.norm()`.

### numpy.exp

In [ ]:
print("np.exp(a):")
np.exp(a)

### numpy.log

In [ ]:
print("np.log(a):")
np.log(a)

### numpy.sqrt

In [ ]:
print("np.sqrt(a):")
np.sqrt(a)

**D:** Identificare almeno un'altra funzione matematica fornita da NumPy.

## Operazioni su un asse specifico

In [ ]:
a = np.arange(12).reshape((3, 4))
print('a:')
print(a)

### Su tutti gli assi

In [ ]:
print("a.max():")
a.max()

### Sulle righe

In [ ]:
print("a.max(axis=0):")
a.max(axis=0)

### Sulle colonne

In [ ]:
print("a.max(axis=1):")
a.max(axis=1)

## Esercizio

Calcolare il valor medio di ogni colonna.

## Accedere agli elementi di un array

In [ ]:
a = np.arange(12).reshape((4, 3))
print('a:')
print(a)

In [ ]:
print("Elemento della seconda riga, terza colonna, a[1, 2]:")
print(a[1, 2])
print("\nPrima riga, a[0, :]:")
print(a[0, :])
print("\nSeconda colonna, a[:, 1]:")
print(a[:, 1])
print("\nSeconda e terza riga, a[1:3, :]:")
print(a[1:3, :])
print("\nUltime due colonna, a[:, -2:]:")
print(a[:, -2:])
print("\nRighe in ordine inverso, a[::-1, :]:")
print(a[::-1, :])

## Esercizo

Creare l'array
```python
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]]
```
Selezionare gli elementi della seconda e terza riga, seconda, terza e quarta colonna:

```python
[[ 5,  6,  7],
 [ 9, 10, 11]]
```

## Unire più array

In [ ]:
a = np.arange(4).reshape((2, 2))
b = np.arange(4, 8).reshape((2, 2))

print('a:')
print(a)
print("\nb:")
print(b)

### numpy.hstack (orizzontalmente)

In [ ]:
np.hstack([a, b])

### numpy.vstack (verticalmente)

In [ ]:
np.vstack([a, b])

## Copie e viste

### Vista (view)

In [ ]:
a = np.arange(5)
b = a
print('a:')
print(a)

print("\nb:")
print(b)

print("\nb è a?")
print(b is a)

print("\nModifico b...")
b[2] = -1

print("\nb:")
print(b)

print("\na:")
print(a)

### Copia (copy)

In [ ]:
a = np.arange(5)
b = a.copy()
print('a:')
print(a)

print("\nb:")
print(b)

print("\nb è a?")
print(b is a)

print("\nModifico b ...")
b[2] = -1

print("\nb:")
print(b)

print("\na:")
print(a)

## Esercizio

Completare la funzione `minimi_quadrati_ricorsivi` nel file lab_00.py implementando il punto 2. dell'algoritmo ricorsivo dei minimi quadrati semplificato (vedi sotto).

**Algoritmo ricorsivo dei minimi quadrati (semplificato):**
1. $\hat{\beta} = 0_{p\times1}$, $V = I_{p\times p}$ (matrice identità $p\times p$)
2. Ciclo per $n = 0, 1, \dots$
    1. $h = 1 / (1 + x_n^{\top}Vx_n)$
    2. $e = y_n - x_n^{\top}\hat{\beta}$
    3. $\hat{\beta} = \hat{\beta} + hVx_ne$
    4. $V = V - hVx_nx_n^{\top}V$
    
    
Per ulteriori dettagli consultare pagina 33 e 34 del libro B. Scarpa e A. Azzalini, Data Analysis and Data Mining.

**Extra 1:** Modificare l'algoritmo in modo da ottenere ad ogni iterazione lo errore standard della stima.

**Extra 2:** Ottenere i valori iniziali di beta e V implementando i punti da 1. a 4. di pagina 34.

In [ ]:
beta = np.array([[2], 
                 [5]])
print("beta:")
print(beta)

num_oss = 1000

X = np.hstack([np.ones((num_oss, 1)), np.random.random((num_oss, 1))])
print("\nprime cinque righe di X:")
print(X[:5])

y = X.dot(beta) + np.random.normal(0, 1.5, (num_oss, 1))
print("\nprimi cinque valori di y:")
print(y[:5])

Inizializzare $\beta$ e V come nel punto 1. dell'algoritmo semplificato o come nel punto **Extra 2**. Nel secondo caso è necessario modificare anche la cella sotto per non utilizzare più volte le stesse osservazioni.

In [ ]:
print("Inizializzo beta e V:")

beta_iniz = np.zeros((2, 1)) # TODO
print("\nbeta:")
print(beta_iniz)

V_iniz = np.diag(np.ones(2)) # TODO
print("\nV:")
print(V_iniz)

In [ ]:
import numpy
from numpy.linalg import inv

def minimi_quadrati_ricorsivi(xn, yn, beta, V):
    h=1/(1+numpy.dot(numpy.dot(xn.T,V),xn))
    e=yn-numpy.dot(xn.T, beta)
    beta=beta+h*e*numpy.dot(V, xn)
    V=V-h*numpy.dot(numpy.dot(V,xn), numpy.dot(xn.T,V))
    return beta, V

def minimi_quadrati(X, y):
    return numpy.dot(inv(numpy.dot(X.T,X)),numpy.dot(X.T,y))

In [ ]:
Implementazione usando

In [ ]:
def minimi_quadrati_ricorsivi(xn, yn, beta, V):
    h = 1 / (1 + numpy.dot(numpy.dot(xn.T, V), xn))
    e = yn - numpy.dot(xn.T, beta)
    beta += h * e * numpy.dot(V, xn)
    V -= h * numpy.dot(numpy.dot(V, xn), numpy.dot(xn.T, V))
    return beta, V

def minimi_quadrati(X, y):
    return numpy.dot(inv(numpy.dot(X.T,X)),numpy.dot(X.T,y))

In [ ]:
np.random.seed(42)
x = np.linspace(0, 1, 100)

beta_mqr = beta_iniz
V_mqr = V_iniz

for ii, (xi, yi) in enumerate(zip(X, y)):
    beta_mqr, V_mqr = minimi_quadrati_ricorsivi(xi[:, np.newaxis], yi, beta_mqr, V_mqr)
    if (((ii + 1) % 20 == 0) & (ii < 100)) or ((ii + 1) % 200 == 0):
        print("\nStima di beta dopo {} osservazioni:".format(ii + 1))
        print(beta_mqr.round(2))
        plt.scatter(X[:ii + 1, 1], y[:ii + 1], alpha=0.9)
        plt.ylim([0, 8])
        plt.xlabel("x")
        plt.ylabel("y")
        plt.plot(x, x*beta_mqr[1] + beta_mqr[0], lw=2, ls='--', c='red')
        plt.grid()
        plt.show()
        comando = input("Premere Enter per continuare, q per terminare. ")
        if comando == 'q':
            break   

print("\nbeta:")
print(beta)

beta_mq = minimi_quadrati(X, y)
print("\nStima minimi quadrati di beta:")
print(beta_mq.round(2))

print("\nStima minimi quadrati ricorsivi di beta:")
print(beta_mqr.round(2))

**D:** Come mai le stime minimi quadrati e minimi quadrati ricorsivi non coincidono?

**R:** ...