# Introduzione a NumPy

## Indice
1. [NumPy](#numpy)<br />
2. [`ndarray`](#ndarray)<br />
    2.1 [Creare un array](#creare_array)<br />
    2.2 [Caratteristiche di un `ndarray`](#caratteristiche_array)<br />
    2.3 [Cambiare la forma di un array](#cambiare_forma_array)<br />
    2.4 [Accedere agli elementi di un array](#accedere_elementi)<br />
    2.5 [Unire più array](#unire_array)<br />
    2.6 [Copie e viste di un array](#copie_viste)<br />
3. [Algebra lineare](#algebra_lineare)<br />
    3.1 [Operazioni di base con scalari](#operazioni_scalari)<br />
    3.2 [Prodotto di array](#prodotto_array)<br />
4. [Funzioni](#funzioni)<br />
    4.1 [Funzioni matematiche](#funzioni_matematiche)<br />
    4.2 [Applicare una funzione lungo un asse](#funzioni_asse)<br />

# 1. NumPy <a id=numpy> </a>

Dal [sito ufficiale](http://www.numpy.org/) di NumPy:
> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

>Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Tutorial ufficiale: [Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html).

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%load_ext autoreload
%autoreload 2

# 2. `ndarray` <a id=ndarray> </a>

## 2.1 Creare un array <a id=creare_array> </a>

### `numpy.array()`

In [ ]:
a = np.array(
    [[1, 2, 3], 
     [4, 5, 6]]
)

print("Tipo: {}".format(type(a)))
print("Contenuto della variabile:")
print(a)

### `numpy.arange()`

In [ ]:
a = np.arange(6)

print("Contenuto della variabile:")
print(a)

### `numpy.zeros()`

In [ ]:
a = np.zeros((2, 3))

print("Contenuto della variabile:")
print(a)

### `numpy.ones()`

In [ ]:
a = np.ones((2, 3))

print("Contenuto della variabile:")
print(a)

### `numpy.random.random()`

In [ ]:
a = np.random.random((2, 3))

print("Contenuto della variabile:")
print(a)

### `numpy.empty()`

In [ ]:
a = np.empty((2, 3))

print("Contenuto della variabile:")
print(a)

### Esercizio

Ottenere il seguente array utilizzando esclusivamente `numpy.arange()`:
```python
[10, 20, 30, 40, 50, 60, 70, 80, 90]
```

## 2.2 Caratteristiche di un `ndarray` <a id=caratteristiche_array> </a>

### `numpy.ndarray.ndim`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Numero di dimensioni: {}".format(a.ndim))

### `numpy.ndarray.shape`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Dimensioni: {}".format(a.shape))

### `numpy.ndarray.size`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Numero di elementi: {}".format(a.size))

### `numpy.ndarray.itemsize`

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Dimensione in bytes di ogni elemento dell'array: {}".format(a.itemsize))

###  `numpy.ndarray.dtype `

In [ ]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Tipo degli elmenti dell'array: {}".format(a.dtype))

### Esercizio

Sapendo che il tipo degli elementi è `int64`, avremmo potuto prevedere la dimensione in bytes? Motivare la risposta.

## 2.3 Cambiare la forma di un array <a id=cambiare_forma_array> </a>

###  `numpy.ndarray.reshape() `

In [ ]:
a = np.arange(6)

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nModificare le dimensioni dell'array:")
a = a.reshape(3, 2)
print("a = a.reshape(3, 2)")

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

###  `numpy.diag() `

In [ ]:
a = np.ones(2)

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nCreare una matrice diagonale a partire da un vettore:")
print("a = np.diag(a)")
a = np.diag(a)

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

### Esercizio

Verificare che, se la matrice diagonale che si vuole ottenere è l'identità, si può utilizzare direttamente `numpy.eye()`.

### Esercizio

Creare il seguente array usando `numpy.arange()` e `numpy.diag()`:
```python
[[0 0 0]
 [0 1 0]
 [0 0 2]]
 ```

###  `numpy.ndarray.T `

In [ ]:
a = np.ones((2, 3))

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nTrasporre la matrice:")
print("a = a.T")
a = a.T

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

### `numpy.newaxis`

In [ ]:
a = np.arange(5)

print("Contenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

print("\nAggiungere una dimensione all'array:")
print("a = a[:, np.newaxis]")
a = a[:, np.newaxis] # equivalente a: a[:, None]

print("\nContenuto della variabile:")
print(a)
print("\nDimensioni: {}".format(a.shape))

## 2.4 Accedere agli elementi di un array <a id=accedere_elementi> </a>

In [ ]:
a = np.arange(12).reshape((4, 3))

print("Contenuto della variabile:")
print(a)

print("\nElemento della seconda riga, terza colonna (a[1, 2]):")
print(a[1, 2])

print("\nPrima riga (a[0, :]):")
print(a[0, :])

print("\nSeconda colonna (a[:, 1]):")
print(a[:, 1])

print("\nSeconda e terza riga (a[1:3, :]):")
print(a[1:3, :])

print("\nUltime due colonne (a[:, -2:]):")
print(a[:, -2:])

print("\nRighe in ordine inverso (a[::-1, :]):")
print(a[::-1, :])

## Esercizo

1. Creare (in modo intelligente...) l'array
```python
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]]
```
2. Selezionare gli elementi della seconda e terza riga, seconda, terza e quarta colonna, verificare che il risultato sia uguale a

```python
[[ 5,  6,  7],
 [ 9, 10, 11]]
```

## 2.5 Unire più array <a id=unire_array> </a>

### `numpy.hstack()` (orizzontalmente)

In [ ]:
a = np.zeros((2, 2))
b = np.ones((2, 2))

print('Contenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

print('\nImpilare orizzontalmente "a" e "b":')
print("c = np.hstack([a, b])")
c = np.hstack([a, b])

print('\nContenuto della variabile "c":')
print(c)

### `numpy.vstack()` (verticalmente)

In [ ]:
a = np.zeros((2, 2))
b = np.ones((2, 2))

print('Contenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

print('\nImpilare verticalmente "a" e "b":')
print("c = np.vstack([a, b])")
c = np.vstack([a, b])

print('\nContenuto della variabile "c":')
print(c)

## 2.6 Copie e viste di un array <a id=copie_viste> </a>

### Vista (view)

In [ ]:
a = np.ones(4)

print('Contenuto della variabile "a":')
print(a)

print("\nb = a")
b = a

print('\nContenuto della variabile "b":')
print(b)

print('\n"b" è "a"? {}'.format(b is a))

print('\nModifico "b"...')
b[2] = 0

print('\nContenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

### Copia (copy)

In [ ]:
a = np.ones(4)

print('Contenuto della variabile "a":')
print(a)

print("\nb = a.copy()")
b = a.copy()

print('\nContenuto della variabile "b":')
print(b)

print('\n"b" è "a"? {}'.format(b is a))

print('\nModifico "b"...')
b[2] = 0

print('\nContenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

# 3. Algebra lineare <a id=algebra_lineare> </a>

## 3.1 Operazioni di base con scalari <a id=operazioni_scalari> </a>

In [ ]:
a = np.arange(20, 60, 10).reshape(2, -2)

print("Contenuto della variabile:")
print(a)

print("\nDivido per 10 e aggiungo 5:")
print("a = (a / 10) + 5")
a = (a / 10) + 5

print("\nContenuto della variabile:")
print(a)

## 3.2 Prodotto di array <a id=prodotto_array> </a>

### `*` ([prodotto di Hadamard](https://it.wikipedia.org/wiki/Moltiplicazione_di_matrici#Costruzioni_alternative) o prodotto puntuale)

In [ ]:
a = np.array(
    [[2, 1], 
     [0, 3]]
)
b = np.array(
    [[2, 0], 
     [1, 3]]
)

print('Contenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

print('\nProdotto di Hadamard tra "a" e "b":')
print("c = a * b")
c = a * b

print('\nContenuto della variabile "c":')
print(c)

### Esercizio

Studiare il concetto di [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html). 

Se
```python
a = np.empty((2, 3, 4))
b = np.empty((3, 4))
c = a * b
```
qual è la `shape` di `c`? provare a rispondere e, solo sucessivamente, verificarlo scrivendo l'opportuno codice.

### `numpy.dot()` ([prodotto scalare](https://it.wikipedia.org/wiki/Prodotto_scalare) o [prodotto matriciale](https://it.wikipedia.org/wiki/Moltiplicazione_di_matrici) se `ndim` è uguale a 2)

In [ ]:
a = np.array(
    [[2, 1], 
     [0, 3]]
)
b = np.array(
    [[2, 0], 
     [1, 3]]
)

print('Contenuto della variabile "a":')
print(a)

print('\nContenuto della variabile "b":')
print(b)

print('\nProdotto scalare tra "a" e "b":')
print("c = np.dot(a, b)")
c = np.dot(a, b) # equivalente a: c = a.dot(b)

print('\nContenuto della variabile "c":')
print(c)

### Esercizio

Sia 
```python
a = np.array(
    [[0, -1],
     [1, 2]]
)
```
1. Calcolare l'inversa di $a$ utilizzando la funzione `numpy.linalg.inv()`.
2. Verificare che la matrice ottenuta sia effettivamente l'inversa di $a$ facendo il prodotto (quale?) tra le due matrici.

# 4. Funzioni <a id=funzioni> </a>

## 4.1 Funzioni matematiche <a id=funzioni_matematiche> </a>

### `numpy.sin()`

In [ ]:
a = np.array(
    [[0, np.pi / 6],
     [np.pi / 3, np.pi / 2]]
)

print("Contenuto della variabile:")
print(a)

print("\nSeno degli elementi dell'array:")
print("a = np.sin(a)")
a = np.sin(a)

print("\nContenuto della variabile:")
print(a.round(2))

### `numpy.cos()`

In [ ]:
a = np.array(
    [[0, np.pi / 6],
     [np.pi / 3, np.pi / 2]]
)

print("Contenuto della variabile:")
print(a)

print("\nCoseno degli elementi dell'array:")
print("a = np.cos(a)")
a = np.cos(a)

print("\nContenuto della variabile:")
print(a.round(2))

### Esercizio

Creare nuovi esempi utilizzando le funzioni `numpy.exp()`,  `numpy.log()`,  `numpy.sqrt()`.

### Esercizio

Siano
```python
a = np.array([0.5, np.cos(np.pi / 6)])
b = np.array([np.cos(np.pi / 6), 0.5])
```
1. Ispezionare la funzione  `grafico_due_vettori` in `msbd/grafici/arrays.py`.
2. Verificare che $a \cdot b = |a| \times |b| \times \cos(\theta)$, con $\theta$ angolo tra i due vettori.

> Suggerimento: per $|\cdot|$ vedere `np.linalg.norm()`.

In [ ]:
from msbd.grafici import grafico_due_vettori

a = np.array([0.5, np.cos(np.pi / 6)])
b = np.array([np.cos(np.pi / 6), 0.5])

grafico_due_vettori(a, b)
plt.show()

## 4.2 Applicare una funzione lungo un asse <a id=funzioni_asse> </a>

### Su tutti gli assi

In [ ]:
a = np.array(
    [[-1, 1],
     [-1, 1]]
)

print("Contenuto della variabile:")
print(a)

print("\nMedia su tutti gli assi (np.mean(a)):")
print(np.mean(a)) # equivalente a: a.mean()

### Lungo il primo asse

In [ ]:
a = np.array(
    [[-1, 1],
     [-1, 1]]
)

print("Contenuto della variabile:")
print(a)

print("\nMedia lungo il primo asse (np.mean(a, axis=0)):")
print(np.mean(a, axis=0)) # equivalente a: a.mean(axis=0)

### Lungo il secondo asse

In [ ]:
a = np.array(
    [[-1, 1],
     [-1, 1]]
)

print("Contenuto della variabile:")
print(a)

print("\nMedia lungo il secondo asse (np.mean(a, axis=1)):")
print(np.mean(a, axis=1)) # equivalente a: a.mean(axis=1)

## Esercizio

Sia
```python
a = np.array(
    [
        [[1, 2],
         [3, 4]],
        [[1, 2],
         [3, 4]],
        [[1, 2],
         [3, 4]],
    ]
)
```
Calcolare la media prima lungo il primo, poi lungo il secondo e infine lungo terzo asse. Riflettere sui risultati ottenuti.